//! `filedrop-ffi`: the FFI surface exposing `filedrop-core` to
//! Flutter/Dart. See `docs/FFI_INTERFACE.md` for the full Rust<->Dart API
//! contract and event catalogue.
//!
//! - [`api`] — safe `async fn` surface (`start_server`, `send_files`,
//!   etc.), introspected directly by `flutter_rust_bridge_codegen` to
//!   generate the Dart bindings in `flutter/lib/src/rust/`. This is now
//!   the live FFI boundary (see `frb_generated`, produced by codegen).
//! - [`c_abi`] — the original hand-written `#[no_mangle] extern "C"` ABI.
//!   Superseded by the flutter_rust_bridge-generated bridge as the
//!   boundary Dart actually calls; kept in the workspace (unused by
//!   Dart) as a documented lower-level ABI rather than deleted.
//! - [`events`] — the `FileDropEvent` enum streamed to Dart (Device/
//!   Pairing/Transfer lifecycle events) via an FRB `StreamSink`.
//! - [`runtime`] — process-wide tokio runtime + engine singleton.
//! - `frb_generated` — generated by `flutter_rust_bridge_codegen generate`
//!   (see `flutter_rust_bridge.yaml` at the repo root); not checked in by
//!   hand, regenerate with that command if `api` changes shape.

pub mod api;
pub mod c_abi;
pub mod events;
pub mod runtime;

#[allow(warnings, unused, clippy::all)]
mod frb_generated;

pub use events::FileDropEvent;
